# src/retrieval/retriever.py

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


class RAGRetriever:
    """
    Combines chunk retrieval + summary retrieval to answer questions.
    Uses the VectorStore for similarity search.
    Answers are generated by combining retrieved context — no LLM needed.
    """

    def __init__(self, vector_store, persona: dict):
        self.store = vector_store
        self.persona = persona

    def retrieve(self, query: str, top_k_chunks: int = 5, top_k_summaries: int = 3) -> dict:
        """
        Retrieve relevant chunks and summaries for a query.

        Returns:
            dict with keys: query, chunks, summaries
        """
        chunks = self.store.search_chunks(query, top_k_chunks)
        summaries = self.store.search_summaries(query, top_k_summaries)

        return {
            "query": query,
            "chunks": chunks,
            "summaries": summaries,
        }

    def answer(self, query: str, top_k_chunks: int = 5, top_k_summaries: int = 3) -> str:
        """
        Generate a natural language answer by combining:
        - Retrieved message chunks (raw context)
        - Retrieved summaries (high-level context)
        - Persona data (user profile)

        No external LLM — assembles answer from retrieved evidence.
        """
        retrieved = self.retrieve(query, top_k_chunks, top_k_summaries)

        # build context from summaries
        summary_context = "\n".join(
            f"- {s['summary']}" for s in retrieved["summaries"]
        )

        # build context from chunks
        chunk_context = "\n\n".join(
            f"[Messages {c['start_index']}–{c['end_index']}]:\n{c['text']}"
            for c in retrieved["chunks"]
        )

        # build persona context
        persona_lines = []
        for habit in self.persona.get("habits", [])[:3]:
            persona_lines.append(f"- Habit: {habit['value']}")
        for fact in self.persona.get("personal_facts", [])[:3]:
            persona_lines.append(f"- Fact: {fact['value']}")
        for trait in self.persona.get("personality_traits", [])[:3]:
            persona_lines.append(f"- Trait: {trait['value']}")
        persona_context = "\n".join(persona_lines)

        answer = f"""Query: {query}

--- Relevant Summaries ---
{summary_context}

--- Relevant Conversation Excerpts ---
{chunk_context}

--- User Persona ---
{persona_context}
"""
        return answer


# ── Manual test ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    import json
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from config import (
        EMBEDDING_MODEL, FAISS_DIR, PERSONA_FILE,
        TOP_K_CHUNKS, TOP_K_SUMMARIES
    )
    from src.vectorstore.store import VectorStore

    logging.basicConfig(level=logging.INFO)

    store = VectorStore(model_name=EMBEDDING_MODEL, faiss_dir=FAISS_DIR)
    store.load()

    with open(PERSONA_FILE) as f:
        persona = json.load(f)

    retriever = RAGRetriever(store, persona)

    queries = [
        "What are their hobbies?",
        "Do they have any pets?",
        "What kind of person is this user?",
    ]

    for q in queries:
        print(f"\n{'='*60}")
        print(retriever.answer(q))